version: 0.0 
os: linux 
files: 
  - source: /spring_boot.tar.gz 
    destination: /home/ec2-user/ 
hooks: 
 # BeforeInstall: 
 #   - location: scripts/stop_server.sh 
 #     timeout: 300 
 #     runas: root 
  AfterInstall: 
    - location: scripts/install_next_release.sh 
      timeout: 300 
      runas: ec2-user 
    - location: scripts/start_server.sh 
      timeout: 300 
      runas: root

